# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18853f8a1ad93823f7ee7e91bb53457e1265b0802d696e45351c44204ed704cb57e7ceb06ca32dcb8447905cfaa2e91996d674522736c9e3210800910d3e7060

test:
  secret_key_base: 2d5e5dbde7e38524057583d484fd4f389f2ac6b6107d332f4977b6adefdff4e6fbf3316e0d4f1775ddd260ad1cc7e3b8f61a5f45a89ee42ec1afaa01b341ba45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
